### PR TITLE
Remove old labels `yelp.com/paasta_`

### PR DESCRIPTION
**Pull request by Bronek**
This is rather intrusive change, let's apply it while the number of impacted services is still relatively low.

### CODE REVIEW

**Comment by Bronek** [comment]
> Seems good to me overall. I'm not a paasta repo expert, but looks good for Kafka :)
> 
>     * Is the `yelp.com/paasta_service` label in [paasta_tools/setup_kubernetes_crd.py](https://github.com/Yelp/paasta/blob/cd520ec556ee4161eed0d03cf1ca405c36634441/paasta_tools/setup_kubernetes_crd.py#L119) left here on purpose?
> 
>     * Ditto for [tests/test_cleanup_kubernetes_jobs.py](https://github.com/Yelp/paasta/blob/cd520ec556ee4161eed0d03cf1ca405c36634441/tests/test_cleanup_kubernetes_jobs.py#L33)

oops, I missed these - thank you!

**Comment by ronin13** [comment]
Can we document the side-effects of this change in the PR.  Can this be applied in-place or does this require   re-creation of objects (statefulsets, deployments etc.). Thanks.

**Comment by Bronek** [comment]
> Can we document the side-effects of this change in the PR. Can this be applied in-place or does this require re-creation of objects (statefulsets, deployments etc.). Thanks.

This will replace the definition of the k8s objects which are owned by Paasta, which typically does *not* include StatefulSets etc. since such objects are owned by their respective k8s operators, rather than Paasta. Since the only (production ready) k8s operator that we currently have is Flink, the impact will be mostly limited to Flink cluster.

**Comment by mattmb** [comment]
Cleaning up and closing some very old PRs

**Pull request closed without merging**
