### PR TITLE
Document which config entries invoke a bounce

### PR DESCRIPTION
**Pull request by solarkennedy**
cc @mittonk

internal ticket PAASTA-4400

I'm also trying out this autorun thing so we don't have to "remember" to keep docs in sync with code.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Fixes #474

**Comment by Rob-Johnson** [comment]
the autorun thing is cool. ty for doing this, shipit!

**Comment by nhandler** [comment]
Assuming the generated docs turned out as expected, Ship It!

**Comment by mittonk** [comment]
Looks good to me in this view, but I saw a missing quote in a rendered view at some point in this process.

**Comment by solarkennedy** [comment]
fixed

**Pull request merged**
