### PR TITLE
Updated /state endpoint for mesos 0.25.x upgrade

### LINKED ISSUE #232: Rename /state.json endpoint in conjunction with mesos 0.24.x to 0.25.x upgrade
In the mesos notes on upgrading from 0.24.x to 0.25.x, they note that the `/state.json` endpoint is becoming `/state`. We use this endpoint in at least one place: https://github.com/Yelp/paasta/blob/67793d2fe99a7f503add185fb8ad92b1a039e436/paasta_tools/mesos_tools.py#L276

This will need to be fixed when we do the mesos upgrade.

Note: A few other endpoints are being renamed, but I was not able to find references to them from a quick grep through our code.

### PR DESCRIPTION
**Pull request by ameya-pandilwar**
Fixes #232

### CODE REVIEW

**Comment by solarkennedy** [comment]
Whoa! Thanks!
However this does cause this test to fail:
https://travis-ci.org/Yelp/paasta/jobs/112490863#L4943

**Comment by keshavdv** [comment]
It would be great if this could fall back to /state.json if /state returns a 404 so that the code remains backward compatible with older versions of Mesos.

**Comment by Rob-Johnson** [comment]
thanks for this @ameya-pandilwar 

the /state endpoint wasn't introduced until mesos 0.25.x, and we run 0.23.x in our tests (and in production) - so won't be able to use it just yet.

It'd be great if you could check for the version and change the endpoint used accordingly? or, as @keshavdv suggested, just fallback to it if /state fails?

**Comment by ameya-pandilwar** [comment]
Fixed the broken test, @solarkennedy !

Introduced a fallback to the backward compatible `/state.json` as @keshavdv suggested. FYI, @Rob-Johnson

**Comment by solarkennedy** [comment]
Super. Thanks!

**Pull request merged**
