### PR TITLE
Use marathon 1.4.0 rc3 in itests

### PR DESCRIPTION
**Pull request by solarkennedy**
For https://github.com/mesosphere/marathon/issues/4769

### CODE REVIEW

**Comment by nhandler** [comment]
Looks like your build is failing looking for marathon. 1.4.0-0.1.20161021221011.snap19.ubuntu1404 appears to be the latest version available.

**Comment by solarkennedy** [comment]
The new marathon bash -> java wrapper can't handle singleton cli args (`--mesos_authentication`) as the final arg :(

**Comment by solarkennedy** [comment]
More python library changes needed:
```
          for hcr in (health_check_results or []) if any(health_check_results)
        File "/tmp/local/lib/python2.7/site-packages/marathon/models/base.py", line 35, in from_json
          return cls(**{to_snake_case(k): v for k, v in attributes.items()})
      TypeError: __init__() got an unexpected keyword argument 'instance_id`
```

**Comment by solarkennedy** [comment]
OMG GREEN BUILD

**Pull request merged**
