### PR TITLE
Added pyramid_swagger to paasta-api

### PR DESCRIPTION
**Pull request by huadongliu**
Main changes:
1. api input/output validation with swagger.json.
2. install swagger.json to paasta_tools_path/api/api_docs via package_data.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Fancy! I say ship.

**Comment by EvanKrall** [comment]
Can we put swagger.json somewhere besides /etc? I think /etc/ is more for configuration, whereas swagger.json is data produced by the package. Probably belongs in /usr/share or something.


Plus, I think our puppet purges /etc/paasta, so we'd just end up deleting swagger.json anyway.

**Comment by huadongliu** [comment]
The last updated addressed @EvanKrall comment to install swagger.json to paasta_tools_path/api/api_docs via package_data, similar to cli/schemas/*.json files.

**Comment by EvanKrall** [comment]
Ship!

**Pull request merged**
