### PR TITLE
try using summary in maintenance

### PR DESCRIPTION
**Pull request by Rob-Johnson**
@mattmb primary

there are no itests for maintenance mode, right? I'll go slowly when I ship this one

### CODE REVIEW

**Comment by solarkennedy** [comment]
Ship

**Comment by nhandler** [comment]
I guess ship it and test it carefully. Without itests, this is tricky to test properly.

**Comment by mattmb** [comment]
Looking at the code I'm 99% sure this should be fine 👍 

🐑 🐑 🐑

**Comment by Rob-Johnson** [comment]
er, this is merged, but github got confused because I didn't base from master. closing.

**Pull request closed without merging**
