### PR TITLE
Make paasta emergency-stop kill an apps tasks harder

### PR DESCRIPTION
**Pull request by solarkennedy**
I guess just be more honest about what emergency stop does?

### CODE REVIEW

**Comment by mattmb** [comment]
This doesn't change that much right? setup_marathon will still correct the state next time it runs?

Shipit

**Comment by Rob-Johnson** [comment]
shipit.

**Comment by solarkennedy** [comment]
Correct. That is why the goal here (I think) was to clarify what this thing does?)

**Comment by solarkennedy** [comment]
Eh, I need to fix up the itest on this one.

**Comment by solarkennedy** [comment]
I still can't get this to work :( :( :(

I'm going to try to extract out these changes into smaller PRs and maybe it will be come more clear?

**Pull request closed without merging**
