### PR TITLE
Fix wait_for_deployment with not enough instances

### PR DESCRIPTION
**Pull request by solarkennedy**
Whoops

### CODE REVIEW

**Comment by solarkennedy** [comment]
Foiled by the tests that are somehow waiting forever...

**Comment by solarkennedy** [comment]
@somic do you have time to investigate this? In theory this "one character" change will help improve the situation where users are needlessly waiting, but you will have to investigate how the tests are waiting.

**Comment by solarkennedy** [comment]
Related to #1169

**Comment by EvanKrall** [comment]
I can try to work on this later today, but if someone else has time first, please take it.

**Comment by somic** [comment]
It appears to be timing out in instance3 block of test_instances_deployed

**Comment by somic** [comment]
https://github.com/Yelp/paasta/blob/master/tests/cli/test_cmds_wait_for_deployment.py#L134

In instance3 block, instances_out queue is empty at the end so a blocking get() waits forever.

**Comment by somic** [comment]
This fixes tests but I haven't wrapped my head around the code enough yet to say if it's the right fix:

```
diff --git i/tests/cli/test_cmds_wait_for_deployment.py w/tests/cli/test_cmds_wait_for_deployment.py
index 3f790f6..ff59a8f 100644
--- i/tests/cli/test_cmds_wait_for_deployment.py
+++ w/tests/cli/test_cmds_wait_for_deployment.py
@@ -131,7 +131,7 @@ def test_instances_deployed(mock_get_paasta_api_client, mock__log):
     instances_out = Queue()
     f(cluster_data, instances_out, e)
     assert cluster_data.instances_queue.empty()
-    assert instances_out.get(block=True) == 'instance3'
+    assert instances_out.empty()

     cluster_data.instances_queue = Queue()
     cluster_data.instances_queue.put('instance4')
```

**Comment by somic** [comment]
@solarkennedy @EvanKrall ^^ - I want to make sure this doesn't just fix the tests but ensures correct behavior.

**Comment by solarkennedy** [comment]
Hmm. I really don't know. @oktopuz you wrote these tests, can you help answer if why my change in the diff would require the change in the tests that @somic proposes?

**Comment by oktopuz** [comment]
I suspect I used 'block=True' accidentally, it should be 'block=False' everywhere in tests.
@somic, given your change, you're right the queue should be empty in this case.

Could you replace 'block=False' with 'block=True' for all other cases in test_instances_deployed() as well?

**Comment by somic** [comment]
I pushed my changes to this PR. @oktopuz please take a look

**Comment by solarkennedy** [comment]
I approve

**Comment by oktopuz** [comment]
lgtm

**Pull request merged**
