### PR TITLE
Handle connection errors to chronos in check_chronos_jobs gracefully

### PR DESCRIPTION
**Pull request by ammaraskar**

### CODE REVIEW

**Comment by solarkennedy** [comment]
This only happens once ever, but chronos may go away later. Can you extend the try/except to include all the of the chronos api interactions?

**Comment by ammaraskar** [comment]
Done

**Comment by solarkennedy** [comment]
Is it? The main for-loop is still not covered here.

**Comment by ammaraskar** [comment]
Oh so that's what you meant, ack, will fix.

**Comment by ammaraskar** [comment]
Actually done

**Comment by solarkennedy** [comment]
ship

**Pull request merged**
