### PR TITLE
Remove yelpy links to jenkins pipeline

### PR DESCRIPTION
**Pull request by kkellyy**
Let's reimplement this in #710 in a more generic way.

### CODE REVIEW

**Comment by nhandler** [comment]
Looks good to me. Let me know when you are ready to actually ship this change.

**Comment by EvanKrall** [comment]
We should make this configurable through SystemPaastaConfig (but not necessarily make @kkellyy do that work, so I'm okay merging this for now.)

**Comment by solarkennedy** [comment]
Would you guys care if we removed this feature entirely?

**Comment by nhandler** [comment]
I think until it becomes easier to discover these pipelines in the Jenkins UI, it is nice to have. But if anyone has strong feelings about removing it, I would be fine with that. Jenkins really isn't a strict dependency of PaaSTA, and this piece of code is a Yelpism.

**Comment by solarkennedy** [comment]
Even at yelp with y-m jenkins isn't used like that. And with this change as it, it will be incorrect. I would rather not even report it, so my vote goes to simply remove it. I don't think you need to be reminded of a jenkins url every time you run status.

**Comment by EvanKrall** [comment]
I'm okay with killing it, potentially replacing this with something similar to `dashboard_links`.

**Comment by kkellyy** [comment]
I don't really mind moving it, but I'm curious if other ways to discover these pipelines exists. If they don't then it might be best to merge this now and eventually remove this yelpism later.

**Comment by solarkennedy** [comment]
But if you merge now, won't all the links be "wrong"? I would rather just remove the link if it is going to be wrong.

**Comment by kkellyy** [comment]
Only wrong if we deployed it immediately. This link is soon to be right.

**Comment by tub** [comment]
Remember that this is also effects the `paasta check` command which compares the Jenkins pipeline to the soa configs.
I'm not against removing that check, but it should be part of a larger refactor that properly separates paasta and the soa-configs (or at least makes it pluggable).

**Comment by solarkennedy** [comment]
@kkellyy we agreed to remove this yelpism from the code base in favor of something more generic.

Can you make this PR more "red" by removing all references to jenkins?

**Comment by solarkennedy** [comment]
@kkellyy can you merge or rebase?

Also be sure to run tox and see flake8 issues.

**Comment by solarkennedy** [comment]
I've rebased and merged.

**Pull request merged**
