### PR TITLE
Make paasta stop/start/restart not print the same type of message rep…

### PR DESCRIPTION
**Pull request by ammaraskar**
…eatedly

### CODE REVIEW

**Comment by Rob-Johnson** [comment]
Can we instead move the code we had above the loop on line 181 so that it only prints once for all instances? Seems the 'simpler' option - you're adding a lot of complexity here.

**Comment by ammaraskar** [comment]
Sure, this was just meant to be expandable in case we add more commands or different components that can be started/stopped.

**Comment by Rob-Johnson** [comment]
yeah, we can do that when we come to it - take the simple approach for now.

**Comment by ammaraskar** [comment]
Replaced with much simpler implementation

**Comment by Rob-Johnson** [comment]
ship

**Pull request merged**
