### PR TITLE
Make the argparser print the full help whenever an argparse issue is encountered

### PR DESCRIPTION
**Pull request by solarkennedy**
The python arparser isn't very helpful when you ask for "help" or typo or a command or something like that, it simply prints the "usage" which is the

```
check,cook-image,emergency-restart,emergency-scale,emergency-start,emergency-stop,fsm,generate-pipeline,get-latest-deployment,info,itest,list,list-clusters,local-run,logs,mark-for-deployment,metastatus,performance-check,push-to-registry,rollback,security-check,start,restart,stop,status,validate
```
message. Not that helpful. This makes it so we print the full help page and respond to the "help" command.

### CODE REVIEW

**Comment by EvanKrall** [comment]
There's really not a way to do this besides subclassing?

Also can you paste the output of `paasta help` with this change?

**Comment by solarkennedy** [comment]
With this change, `paasta help` will return the same thing as `paasta --help`: http://pastebin.com/7JTdVHJR

Yes, I believe this is the only way with python-argparse to prevent it from spitting out the terse "usage" text on error:
http://stackoverflow.com/questions/14728376/i-want-python-argparse-to-throw-an-exception-rather-than-usage

**Comment by solarkennedy** [comment]
ping @EvanKrall

**Comment by EvanKrall** [comment]
Shipit

**Pull request merged**
