### PR TITLE
Use docker containerizer to run itests.

### LINKED ISSUE #373: Use docker containerizer in itests
When running PaaSTA, we set the mesos containerizer to `docker`. However, we do not specify a containerizer currently for our itests. This causes it to default to `mesos`. To ensure we are testing a setup like the one we actually run, we should update the itests to use the `docker` containerizer. This will also likely allow us to stop specifying `--launcher=posix` when running mesos.

### PR DESCRIPTION
**Pull request by matthewbentley**
TL;DR: this tells the mesosslave to use docker to run itests, and bind mounts /var/run/docker.sock and /usr/bin/docker into the mesosslave(s) to use the host's docker.
It also updates a bunch of tests to actually work in docker
Closes #373
Should be followed up by something to deal with #576

### CODE REVIEW

**Comment by matthewbentley** [comment]
`make itest` works, but I'm not sure how this will interact with travis

**Comment by Rob-Johnson** [comment]
this is great.

shipit!

**Comment by matthewbentley** [comment]
OK, pretend I didn't try to pin the right docker version. If this travis build passes, we're probably good to go.

**Comment by matthewbentley** [comment]
Well, it failed. That was unexpected. I guess we have tests for a reason

**Comment by EvanKrall** [comment]
Ship!

**Pull request merged**
