### PR TITLE
Allow users to set accepted_resource_roles in marathon yamls.

### PR DESCRIPTION
**Pull request by EvanKrall**
internal ticket PAASTA-2455.

This passes the `accepted_resource_roles` parameter through marathon.yaml into the marathon config, allowing for apps to be deployed to dedicated hardware.

### CODE REVIEW

**Comment by nhandler** [comment]
You will also need to update `paasta_tools/cli/schemas/marathon_schema.json`

**Comment by solarkennedy** [comment]
Can you update the docs as well?

This is going to cause a big bounce too right? :(

**Comment by EvanKrall** [comment]
@solarkennedy Yeah, this would cause a large bounce.

We could avoid that by using the `--default_accepted_resource_roles` command line parameter for Marathon, and omit `accepted_resource_roles` from the formatted marathon dict if it's not specified.

Should I try to do that?

**Comment by EvanKrall** [comment]
I've made it so that the config dict doesn't contain `accepted_resource_roles` if it's not specified in your marathon.yaml

**Pull request merged**
