### PR TITLE
Fix example_cluster

### PR DESCRIPTION
**Pull request by mattmb**
The pip step was hanging for me. Seemed to be a setuptools bug of some
sort. This should upgrade and pin setuptools in the container.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you look at the example_cluster changes in #1391 to see if they are relevant?

**Comment by asottile** [comment]
The only useful part of this patch (imo) is the `-r` (which was incorrect before and did nothing).  The hang isn't related to setuptools version but the `gevent` build itself (which is flakey).

**Comment by mattmb** [comment]
I didn't do much to debug to be honest, this was just the first thing that I tried and it "worked". Just a coincidence I guess @asottile? Is the gevent flakiness "random"?

**Comment by asottile** [comment]
Yeah it seemed random to me.  

Honestly a better fix would be factoring out gevent, it is unlikely to perform better than `multiprocessing` and is currently only used for two things:
- paasta api (could easily be replaced with a more-robust uwsgi solution)
- autoscaling lib stats retrieval (should really be using `multiprocessing.Pool`)

Plus, removing it will improve each virtualenv setup by nearly a minute

**Pull request closed without merging**
