### PR TITLE
Upgrade mesos to 0.23.1-0.2.61.ubuntu1404

### PR DESCRIPTION
**Pull request by nhandler**
Following http://paasta.readthedocs.org/en/latest/upgrading_mesos.html . This is step 1 to bump the version of Mesos that is installed in the integration tests.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you double check this and branch off of master?

**Comment by nhandler** [comment]
Oops. I just went ahead and fixed that.

**Comment by solarkennedy** [comment]
We reference this in a few other places, can you make sure to get all (3) ?

**Comment by solarkennedy** [comment]
ship if the tests pass. Cancel 3866 if you are impatient.

**Pull request merged**
