### PR TITLE
Add http://pre-commit.com hooks

### PR DESCRIPTION
**Pull request by asottile**
I've noticed that style is somewhat inconsistent.  Let's add some automated fixing :D

Almost all of this is entirely automated, the interesting bits are in .pre-commit-config.yaml and tox.ini

### CODE REVIEW

**Comment by asottile** [comment]
Fixed the conflicts

**Comment by Rob-Johnson** [comment]
this is great, thankyou!

**Comment by solarkennedy** [comment]
Sorry @asottile, more conflicts. Can you rebase one more time?

**Comment by asottile** [comment]
@solarkennedy fixd!

**Comment by solarkennedy** [comment]
I'm happy to eat our own dogfood and I'm happy to see our codebase become that much more consistent. Thanks!

**Pull request merged**
