### PR TITLE
Small itest fixes for marathon itests

### PR DESCRIPTION
**Pull request by solarkennedy**
Hopefully making itests slightly faster.

### CODE REVIEW

**Comment by nhandler** [comment]
Ship It if tests pass

**Comment by Rob-Johnson** [comment]
shipit

**Comment by solarkennedy** [comment]
Hah, it is so fast that these failing itests assume that by the time it shows up in marathon it is *healthy*!
I think I would rather make these tests relax their assertions and just by happy that a task is running in marathon at all, even if it isn't considered healthy yet?

**Comment by solarkennedy** [comment]
This failing test is bogus and only ever worked because of time.
I needs to be fixed in a different way.

**Pull request merged**
