### PR TITLE
Move version number to paasta_tool's __init__

### PR DESCRIPTION
**Pull request by ammaraskar**

### CODE REVIEW

**Comment by solarkennedy** [comment]
ship

**Comment by EvanKrall** [comment]
Why?

**Comment by ammaraskar** [comment]
So it can be access programatically, we're making our web requests sent along a user-agent header so it would be nicer having something like "Paasta Tools v0.38.x" as the agent.

**Comment by EvanKrall** [comment]
Cool, makes sense.

**Pull request merged**
