### PR TITLE
Dump subcommands information into json for consumption by other commands

### PR DESCRIPTION
**Pull request by mks-m**
golang binary could use this for printing help messages or generating autocompletion, etc

### CODE REVIEW

**Comment by solarkennedy** [comment]
This is interesting... does it work?

I don't consider this a "public" command, can you move it out of the main `paasta` part and into something like `paasta_dump_command_choices` or something? That way it isn't in the "critical" path of the main paasta command, doesn't slow it down, etc.

**Comment by keymone** [comment]
it does work, i don't know if we really need it, maybe eventually, i'll just let it sit here for now

**Comment by solarkennedy** [comment]
@keymone Are you still planning on taking this approach?

**Comment by keymone** [comment]
yes, eventually, it's a bit low on priorities list.

**Comment by mattmb** [comment]
Cleaning up and closing some very old PRs. Please re-open or nudge me if you’re still planning to work on this.

**Pull request closed without merging**
