### PR TITLE
Only have travis build on master (and pull requests).

### PR DESCRIPTION
**Pull request by EvanKrall**
This should lighten the load on Travis and thus get us feedback sooner.

### CODE REVIEW

**Comment by EvanKrall** [comment]
(see that this branch is not included on https://travis-ci.org/Yelp/paasta/branches)

**Comment by nhandler** [comment]
Based on the fact that travis is only trying to run the `continuous-integration/travi-ci/pr` check, it looks like your change is fine.

Ship It!

**Comment by mjksmith** [comment]
This is pretty sweet. I've always wondered why we check both branches and prs since we really only care about tests passing after a change is merged (aka what travis/pr checks)

**Comment by nhandler** [comment]
The additional travis check was initially added so that you can iterate on a branch and get some test feedback as you go. However, for most of our branches, we open a PR shortly after pushing the branch to Github, so building all of the branches isn't necessary.

**Pull request merged**
