### PR TITLE
Drop all capabilities by default in docker containers.

### PR DESCRIPTION
**Pull request by solarkennedy**
I got lazy and copy pasted in the tests.

### CODE REVIEW

**Comment by mattmb** [comment]
Any chance of somehow making it a SystemPaastaConfig so that you can roll it out with a config change? It'll be another big bounce right which will mean pinning otherwise.

**Comment by mattmb** [comment]
++ on the general idea btw

I also wouldn't be *that* surprised if some service ends up needing one from the list. Maybe it's also worth making it configurable per service?

**Comment by solarkennedy** [comment]
I think we can take another big bounce. Or I can batch it.

I was really hoping to not add yet another configuration option.
I *would* be surprised if we have a service that needs one of those capabilities actually.

**Comment by solarkennedy** [comment]
The tests are failing because of some weird coverage stdout io nonsense?

**Comment by solarkennedy** [comment]
Tests are passing now.

**Pull request merged**
