### PR TITLE
Use v2 deployments

### PR DESCRIPTION
**Pull request by mjksmith**
This removes the v1 deployments json and make all of `paasta_tools` use the new v2 format.

### CODE REVIEW

**Comment by mjksmith** [comment]
This broke since we reverted adhoc instances. I'll clean it up once that gets shipped again.

**Comment by solarkennedy** [comment]
Rebase please :(

**Comment by mjksmith** [comment]
@solarkennedy done

**Comment by solarkennedy** [comment]
I really hope nothing is using v1, this will certainly expose that.

For a final test before shipping can you confirm that only the v1 dict goes away by doing a generate-deployments on yelp-main before and after activating a virtualenv?

If the only difference is the v1 dict, then ship.

**Comment by mjksmith** [comment]
A code search seems to show nothing uses v1 deployments unless they access it in a very weird way. Exempli gratia:
```
deployments_file_name = 'deployments'
deployments_file = '%s.json' % deployments_file_name
with open(deployments_file, 'r'):
    # blah
```

**Comment by mjksmith** [comment]
@solarkennedy confirmed the only difference is the absence of the v1 dict.

**Pull request merged**
