### PR TITLE
Use all the fstrings

### PR DESCRIPTION
**Pull request by solarkennedy**
Consistency in the codebase is a big nice to have.

I used @asottile's flynt command to convert these.

What could possibly go wrong! :)

### CODE REVIEW

**Comment by asottile** [comment]
I didn't write `flynt` and would suggest not using it, it performs unsafe changes

**Comment by asottile** [comment]
(I assume you saw it due to me forking it, I'm currently trying to disassociate my software with it currently since users are confusing it with pyupgrade which performs the same function but with safety checks)

**Comment by solarkennedy** [comment]
Whoops! sorry @asottile I didn't read things closely enough. 
We are running with py3-plus, but not py36-plus! (til).

I'll try this with pyupgrade first and see how it goes. Thanks!

I would send love to you again if there was such a thing cross companies. 💌

**Comment by asottile** [comment]
I'm still in SF :) would be happy to grab lunch or something!

**Comment by asottile** [comment]
and yeah the test failures are flynt doing unsafe things and breaking your code :P

**Pull request closed without merging**
