### PR TITLE
Hooks use python 3 defaults

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
Strange, these both failed in the same way -- any hints as to why this is failing?

**Comment by asottile** [comment]
figured it out, there's an itest container that's still running python2.7

**Comment by asottile** [comment]
I can't reproduce the failures in travis-ci locally with docker-compose

**Comment by solarkennedy** [comment]
I've restarted the paasta_itests because it looks like it failed on apt-get dns stuff.

I'm ok with example_cluster tests being broken temporarily, in fact do you think your changes should be used instead of the ones in #1393?

**Comment by asottile** [comment]
I'm still not entirely sure what's up with this branch -- I plan to debug it a bit more when I have some time (it'll need a rebase at this point now)

**Comment by solarkennedy** [comment]
Take your time, there isn't a rush of course and we really appreciate your help.

**Comment by EvanKrall** [comment]
Which container is running python2.7?

**Comment by asottile** [comment]
I've been trying to tackle the last two here: https://github.com/Yelp/paasta/pull/1435

But I'm hitting a bit of a brick wall -- if you'd like to take over the branch and/or complete/debug it that would be awesome (since I'm mostly doing a bit here and there for fun when I get the chance).

**Comment by solarkennedy** [comment]
@asottile ok to merge?

**Comment by asottile** [comment]
@solarkennedy indeedy!  Thanks for the patience on this one :)

**Comment by solarkennedy** [comment]
We really appreciate your efforts in this!

**Comment by solarkennedy** [comment]
If I can get my proposal to name TVs after past employees, I will be sure to get you immortalized in uzbl config! :) (if that is OK)

**Comment by asottile** [comment]
👍

**Pull request merged**
