### PR TITLE
Properly quote custom paasta local-run command

### PR DESCRIPTION
**Pull request by drolando**
We're double quoting the custom command received via `paasta local-run -C`. This is probably fine if the command is a single word, but it fails if it's something slightly more complex like "make test" since bash will now consider the entire string as the command name.

I'm not sure if this is the best way to check the command inside the docker run args list, but afaik the custom command must always be at the end of the docker run, so this should be fine.

With `pipes.quote`, the test failed like:
```
    def test_get_docker_run_cmd_quote_cmd():
        memory = 555
        random_port = 666
        container_name = 'Docker' * 6 + 'Doc'
        volumes = ['7_Brides_for_7_Brothers', '7-Up', '7-11']
        env = {}
        interactive = True
        docker_hash = '8' * 40
        command = ['make', 'test']
        net = 'host'
        docker_params = []
        actual = get_docker_run_cmd(memory, random_port, container_name, volumes, env,
                                    interactive, docker_hash, command, net, docker_params)

>       assert actual[-3:] == [u'sh', u'-c', u'make test']
E       assert ['sh', '-c', "'make test'"] == ['sh', '-c', 'make test']
E         At index 2 diff: u"'make test'" != u'make test'
E         Full diff:
E         - [u'sh', u'-c', u"'make test'"]
E         ?                 -           -
E         + [u'sh', u'-c', u'make test']

tests/cli/test_cmds_local_run.py:727: AssertionError
```

### CODE REVIEW

**Comment by solarkennedy** [comment]
Woot!

**Comment by lucagiovagnoli** [comment]
thanks @drolando! This is what I was mentioning last week @solarkennedy
+1

**Comment by drolando** [comment]
I just run `python ../../packages/paasta/paasta_tools/cli/cli.py local-run -C 'make test-in-container'` on my devbox and it worked correctly

**Comment by solarkennedy** [comment]
Can you run the general_itests (tox -e general_itests) and make sure they pass too?

**Comment by drolando** [comment]
@solarkennedy @EvanKrall All tests and itests are now passing, but I'd like you to double check my change. I've followed krall's suggestion and stopped converting the command back and forth from string to array. It looks like Popen is able to properly quote stuff, so this now work both interactively and not.

The paasta_itests are flaky. The first time I got a timeout error, but then I rerun them and everything worked. They also passed on my devbox. Is this a known problem?

**Comment by solarkennedy** [comment]
Yea it happens (flakey)

**Pull request merged**
