### PR TITLE
Support pod identity in `spark-run`

### PR DESCRIPTION
**Pull request by nurdann**
## Changes
- Picking up from https://github.com/Yelp/paasta/pull/3787
- `args.no_aws_credentials` was removed in https://github.com/Yelp/paasta/pull/3679 [[error](https://fluffy.yelpcorp.com/i/VHnLpxxbNCxSN5QmdVnt0BMtj1R81C2Q.html)]
- [x] Waiting on being merged https://github.com/Yelp/service_configuration_lib/pull/137
- `get_signalfx_url()` was deleted in https://github.com/Yelp/service_configuration_lib/pull/143
   - Should be safe because the dashboard says that the license has expired

### CODE REVIEW

**Comment by nurdann** [comment]
Manually setting pod identity worked https://fluffy.yelpcorp.com/i/3Gcd1qTzDjNP1z4zKD3t7c4D1d7SHDd8.html

**Comment by nurdann** [comment]
Don't ge why setting `autospec=True` fails for [98b1217](https://github.com/Yelp/paasta/pull/3828/commits/98b1217f925a3a6f3fedbb68d569baed428afad5) with
```
FAILED tests/cli/test_cmds_spark_run.py::test_get_aws_credentials - TypeError: autospec creates the mock for you. Can't specify autospec and new.
```

**Comment by 88manpreet** [comment]
Change lgtm. Can you update the documentation https://yelpwiki.yelpcorp.com/pages/viewpage.action?pageId=283750257, to append the section with following details: 
* In what cases user should use --use-web-identity argument
* An example

If possible would suggest to push on Monday.

**Review by CaptainSame — APPROVED** [review]

**Comment by 88manpreet** [comment]
+1. Thanks for adding in documentation.

**Pull request merged**
