### PR TITLE
Remove tags chronos jobs

### PR DESCRIPTION
**Pull request by Rob-Johnson**
This is going to be a rolling PR.

Current Status: unit tests and integration tests pass. There aren't actually that many changes here, it was mostly work in the integration tests.

Before I merge, I'm going to evaluate the integration tests are still testing 'useful' things. I'll also test on mesosstage.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Hmm. The `get_marathon_services_running_here_for_nerve` test failed? Could easily be a different more rare flake.

Otherwise ship, I think this is about what I expected. Hopefully chronos can tolerate us updating the jobs all the time.

**Comment by Rob-Johnson** [comment]
yeah, this is flaky.

**Comment by Rob-Johnson** [comment]
this looks ok on mesosstage.

**Comment by solarkennedy** [comment]
ship

**Pull request merged**
