### PR TITLE
remove include_temporary from chronos_serviceinit

### PR DESCRIPTION
**Pull request by Rob-Johnson**
unintentionally included in d484d15714f84d7fc1908902520ab8afa2eb376c

### CODE REVIEW

**Comment by mattmb** [comment]
You mean `include_temporary`?

**Comment by Rob-Johnson** [comment]
Ha, I do.

**Comment by mattmb** [comment]
Also, why don't we want to stop 'tmp' jobs? Is it because they are explicitly started by a user rather so paasta should leave them alone?

**Comment by Rob-Johnson** [comment]
Eventually, we do (PAASTA-7038). But I need to finish writing tests and make a proper PR, rather than sneaking a change in with another PR.

**Comment by mattmb** [comment]
Right, thought it sounded familiar. Sounds good, can you amend the commit message before you ship 😄

**Pull request merged**
