### PR TITLE
expose CLI as console_scripts #85

### LINKED ISSUE #85: Expose CLI as console_scripts
http://python-packaging.readthedocs.org/en/latest/command-line-scripts.html#the-console-scripts-entry-point

This'd avoid the confusion I always have when pip installing this and then wondering where `paasta` is.

### PR DESCRIPTION
**Pull request by kentwills**
@solarkennedy, fixes #85.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Hmmm. Can you also look at debian/paasta-tools.links:19?

**Comment by kentwills** [comment]
@solarkennedy, resolved

**Comment by solarkennedy** [comment]
Great! Thanks!

**Comment by EvanKrall** [comment]
Woo, this is exciting. Now I can install the paasta CLI on my laptop :)

**Pull request merged**
