### PR TITLE
Add intermediate venv

### PR DESCRIPTION
**Pull request by mattmb**
I know this is kinda nuts but it does make the tests pass on a dev box.
I'm basically adding an intermediate venv which we install the latest
versions of pip + virtualenv. This way tox creates a virtualenv with
sufficiently new tools to work consistently.

### CODE REVIEW

**Comment by mattmb** [comment]
This is to make the tests pass on Jenkins as well as travis

**Comment by Rob-Johnson** [comment]
why don't we make this run in a container?

**Comment by nhandler** [comment]
A container makes sense, although it will be unfortunate to have that extra overhead for unit tests. But can we merge this and iterate? Not being able to easily run tests locally makes development tougher.

**Comment by Rob-Johnson** [comment]
yeah, shipit so we can do some work today. mmb is OOO, so we can merge it for him.

**Comment by mattmb** [comment]
Thanks for shipping this :-) Looks like we've still got issues with the itests, I'll see if I can apply a similar fix...

I kinda agree that we shouldn't have this in a container. I know we need Docker for the itests but it'd be nice not to make it a dependency on running the unit tests too.

**Pull request merged**
