### PR TITLE
Flesh out docs for smartstack.yaml

### PR DESCRIPTION
**Pull request by EvanKrall**
This adds documentation for all of the keys listed in the `key_whitelist` in marathon_tools.py.

### CODE REVIEW

**Comment by mrtyler** [comment]
1. Is that markdown formatting correct?

2. I assume you copied this from some other (internal) doc? If so, do you have a plan to kill the internal-only one or otherwise prevent the copies from drifting from one another?

**Comment by EvanKrall** [comment]
1. This is ReStructured Text, not Markdown. Code blocks are started by ending the previous line with `::`
2. This is new content, not copied from internally. Our internal docs are more substantial, but somewhat tied to our configuration. I'll try to pull that content into this.

**Comment by solarkennedy** [comment]
Looks fine to me. Could be more RSTy but a well commented config file is just fine by me.

**Comment by EvanKrall** [comment]
I've copied a bunch of info from our internal smartstack docs and RSTified it.

**Pull request merged**
