### PR TITLE
fixed paasta logs -l

### LINKED ISSUE #909: paasta logs -l is broken
```
matts@host:~$ paasta logs -c CLUSTER -C app_output -l 1000 -s SERVICE
Traceback (most recent call last):
  File "/usr/bin/paasta", line 11, in <module>
    load_entry_point('paasta-tools==0.56.5', 'console_scripts', 'paasta')()
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cli.py", line 119, in main
    return_code = args.command(args)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/logs.py", line 1031, in paasta_logs
    log_reader.print_last_n_logs(service, args.line_count, levels, components, clusters, raw_mode=args.raw_mode)
TypeError: print_last_n_logs() takes exactly 8 arguments (7 given)
```

### PR DESCRIPTION
**Pull request by mjksmith**
Fixes #909

### CODE REVIEW

**Comment by solarkennedy** [comment]
ship

**Comment by solarkennedy** [comment]
kwargs would be slightly better and help defend against param ordering bugs

**Comment by mjksmith** [comment]
There's actually a bug in the version of clog we're using -_-

```
matts@hostname:~$ paasta logs -c CLUSTER -C app_output -s SERVICE -a 2016-11-01T00:00:00 -t 2016-11-02T00:00:00
Traceback (most recent call last):
  File "/usr/bin/paasta", line 11, in <module>
    load_entry_point('paasta-tools==0.56.5', 'console_scripts', 'paasta')()
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cli.py", line 119, in main
    return_code = args.command(args)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/logs.py", line 1046, in paasta_logs
    raw_mode=args.raw_mode)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/logs.py", line 715, in print_logs_by_time
    self.run_code_over_scribe_envs(clusters=clusters, components=components, callback=callback)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/logs.py", line 563, in run_code_over_scribe_envs
    callback(component, stream_info, scribe_env, cluster=None)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/logs.py", line 708, in callback
    ctx = self.scribe_get_from_time(scribe_env, stream_name, start_time, end_time)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/logs.py", line 798, in scribe_get_from_time
    return scribereader.get_stream_reader(stream_name, host, port, start_time, end_time)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/scribereader/scribereader.py", line 203, in get_stream_reader
    localS3=localS3)
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/clog/readers.py", line 499, in __init__
    if get_ecosystem(self.host) == 'stagespam':
  File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/clog/readers.py", line 427, in get_ecosystem
    return get_settings['HOST_TO_ECOSYSTEM'][hostname]
TypeError: 'function' object has no attribute '__getitem__'
```

It looks like this was fixed in https://github.com/Yelp/yelp_clog/pull/7 which was included in `yelp-clog` version 2.2.12, but the latest version that was uploaded to pypi is 2.2.11.

**Comment by mjksmith** [comment]
@solarkennedy can you take another look at this with kwargs and the `yelp-clog` update?

**Comment by solarkennedy** [comment]
ship

**Pull request merged**
