### PR TITLE
re-ordered default deploy order in fsm

### PR DESCRIPTION
**Pull request by mjksmith**
This changes the default deploy order to stage -> prod canary -> prod non-canary & dev

@EvanKrall @asottile you can argue for or against this here

### CODE REVIEW

**Comment by asottile** [comment]
nitpick: breaking all four of stages with a bad staging deploy isn't usually the nicest

could we do 1 stage by default and rest-of-stages after?

**Comment by EvanKrall** [comment]
Pull this into a system config file plz

**Comment by mjksmith** [comment]
@asottile this probably won't be implemented now because either we pick a single stage to be the default for every new service, or we make users pick a default stage when they run `fsm`. I'm hesitant to include stage-picking logic in `fsm` since it won't apply to all non-Yelp infrastructures.

**Comment by mjksmith** [comment]
@EvanKrall I forgot to mention this in standup (I thought it was done) but this is ready for more review/to ship

**Comment by solarkennedy** [comment]
This looks fine, just moving it to reading an external config file

**Pull request merged**
