### PR TITLE
PAASTA-17389.

### PR DESCRIPTION
**Pull request by yeryomenkom**
https://jira.yelpcorp.com/browse/PAASTA-17389

### CODE REVIEW

**Review by AshishKhatkar — APPROVED** [review]
looks good to me. Let's wait for someone from CI to review before merging.

**Comment by AshishKhatkar** [comment]
@yeryomenkom  Let's update function `test_paasta_config_flink_dashboard_base_url` as well in `test_setup_kubernetes_cr.py` as well

**Comment by yeryomenkom** [comment]
> @yeryomenkom Let's update function `test_paasta_config_flink_dashboard_base_url` as well in `test_setup_kubernetes_cr.py`

you mean [this](https://github.com/Yelp/paasta/blob/ed64464f042a5280ff1eacb0f0f0557b719c7a76/tests/test_setup_kubernetes_cr.py#L269) should become `"http://flink.mycluster.paasta"` ?

**Comment by AshishKhatkar** [comment]
> > @yeryomenkom Let's update function `test_paasta_config_flink_dashboard_base_url` as well in `test_setup_kubernetes_cr.py`
> 
> you mean [this](https://github.com/Yelp/paasta/blob/ed64464f042a5280ff1eacb0f0f0557b719c7a76/tests/test_setup_kubernetes_cr.py#L269) should become `"http://flink.mycluster.paasta"` ?

Yes

**Review by keymone — APPROVED** [review]

**Review by AshishKhatkar — APPROVED** [review]
lgtm

**Pull request merged**
